development:
  adapter: postgresql
  encoding: unicode
  database: steepl_development
  pool: 5
  timeout: 5000
  user: robert

test:
  adapter: postgresql
  encoding: unicode
  database: steepl_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: steepl_production
  pool: 5
  timeout: 5000
  user: deploy
