development:
  adapter: postgresql
  encoding: unicode
  database: steepl_development
  pool: 5
  timeout: 5000
  user: robert
  host: 127.0.0.1

test:
  adapter: postgresql
  encoding: unicode
  database: steepl_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: steepl_production
  pool: 5
  timeout: 5000
  user: steepl
