#!/home/deploy/.rbenv/shims/ruby

APP_FOLDER='/usr/local/steepl'
APP_ROOT="#{APP_FOLDER}/current"
UNICORN_PID="#{APP_FOLDER}/shared/pids/unicorn.pid"


@deploy_time = Time.now.strftime('%Y%m%d%H%M%S')
@latest_folder = "#{APP_FOLDER}/#{@deploy_time}"


def create_links
  puts 'Creating Symlinks'
  `rm -rf #{APP_ROOT}`
  `ln -s #{@latest_folder} #{APP_ROOT}`
  `ln -s #{APP_FOLDER}/shared #{APP_ROOT}/`
end

def checkout_new_version
  `unset $(git rev-parse --local-env-vars)`
  puts "Cloning repo into #{@latest_folder}"
  `git clone /home/deploy/steepl.git #{@latest_folder}`
end

def run_bundle
  puts 'running bundle install'
  puts `cd #{APP_ROOT} && bundle install --without development test`
  puts `rbenv rehash`
end

def precompile_assets
  puts 'Precompiling Assets'
  puts `cd #{APP_ROOT} && rake assets:precompile`
  puts `rake steepl:non_digested`
end

def restart_unicorn
  puts 'Restarting Unicorn'
  `service unicorn restart`
end

def refresh_whenever
  puts`whenever --update-crontab`
end

puts 'Receiving new version of Steepl'
checkout_new_version
create_links
run_bundle
precompile_assets
refresh_whenever
restart_unicorn

exit 0
